import { defineStore } from "pinia";

export const analyticStore = defineStore("analyticStore", {
  state() {
    return {
      managers: managers || null,
      analytic: {
        general: {
          totalRevenue: totalRevenue || null,
          trafficRevenue: trafficRevenue || null,
          additionalRevenue: additionalRevenue || null,
          advExpenses: advExpenses || null,
          kpd: kpd || null,
          sales: sales || null,
          salesTraffic: salesTraffic || null,
          salesMailing: salesMailing || null,
          salesAdditional: salesAdditional || null,
          average: average || null,
          averageTrafficMailing: averageTrafficMailing || null,
          averageAdditional: averageAdditional || null,
          profit: profit || null,
          rating: rating || null,
          prescribed: prescribed || null,
          prescribedToSale: prescribedToSale || null,
          shareAdvExpensesTrafficPage: shareAdvExpensesTrafficPage || null,
          advShow: advShow || null,
          advClick: advClick || null,
          advApplication: advApplication || null,
          importantRow: importantRow || null,
          invoices: invoices || null,
          salesNewClient: salesNewClient || null,
          salesNewClientNM: salesNewClientNM || null,
          salesNewClientM: salesNewClientM || null,
          rejectsRow: rejectsRow || null,
          newClientsDo: newClientsDo || null,
          newClientsTraffic: newClientsTraffic || null,
          newClientsAll: newClientsAll || null,
          newClientsWithoutMailing: newClientsWithoutMailing || null,
          newClientsWithMailing: newClientsWithMailing || null,
          averageCheckTraffic: averageCheckTraffic || null,
          showPrice: showPrice || null,
          clickPrice: clickPrice || null,
          applicationPrice: applicationPrice || null,
          importantPriceRow: importantPriceRow || null,
          invoicePrice: invoicePrice || null,
          clientPrice: clientPrice || null,
          clientPriceDo: clientPriceDo || null,
          showToClick: showToClick || null,
          clickToApplication: clickToApplication || null,
          applicationToInvoice: applicationToInvoice || null,
          invoiceToClient: invoiceToClient || null,
          applicationToClient: applicationToClient || null,
          clickToApplicationDo: clickToApplicationDo || null,
          CV5Row: CV5Row || null,
        },
        manager: {
          managerTotalRevenue: managerTotalRevenue || null,
          managerTrafficRevenue: managerTrafficRevenue || null,
          managerAdditionalRevenue: managerAdditionalRevenue || null,
          managerAdvExpenses: managerAdvExpenses || null,
          managerKpd: managerKpd || null,
          managerSales: managerSales || null,
          managerSalesTraffic: managerSalesTraffic || null,
          managerSalesMailing: managerSalesMailing || null,
          managerSalesAdditional: managerSalesAdditional || null,
          managerAverage: managerAverage || null,
          managerAverageTrafficMailing: managerAverageTrafficMailing || null,
          managerAverageAdditional: managerAverageAdditional || null,
          managerProfit: managerProfit || null,
          managerRating: managerRating || null,
          managerPrescribed: managerPrescribed || null,
          managerPrescribedToSale: managerPrescribedToSale || null,
          managerShareAdvExpensesTrafficPage: managerShareAdvExpensesTrafficPage || null,
          managerAdvShow: managerAdvShow || null,
          managerAdvClick: managerAdvClick || null,
          managerAdvApplication: managerAdvApplication || null,
          managerImportantRow: managerImportantRow || null,
          managerInvoices: managerInvoices || null,
          managerSalesNewClient: managerSalesNewClient || null,
          salesMNewClientNM: salesMNewClientNM || null,
          salesMNewClientM: salesMNewClientM || null,
          mRejectsRow: mRejectsRow || null,
          newMClientsDo: newMClientsDo || null,
          newMClientsTraffic: newMClientsTraffic || null,
          newMClientsAll: newMClientsAll || null,
          newMClientsWithoutMailing: newMClientsWithoutMailing || null,
          newMClientsWithMailing: newMClientsWithMailing || null,
          managerAverageCheckTraffic: managerAverageCheckTraffic || null,
          mShowPrice: mShowPrice || null,
          mClickPrice: mClickPrice || null,
          mApplicationPrice: mApplicationPrice || null,
          mImportantPriceRow: mImportantPriceRow || null,
          mInvoicePrice: mInvoicePrice || null,
          mClientPrice: mClientPrice || null,
          mClientPriceDo: mClientPriceDo || null,
          mShowToClick: mShowToClick || null,
          mClickToApplication: mClickToApplication || null,
          mApplicationToInvoice: mApplicationToInvoice || null,
          mInvoiceToClient: mInvoiceToClient || null,
          mApplicationToClient: mApplicationToClient || null,
          mClickToApplicationDo: mClickToApplicationDo || null,
          mCV5Row: mCV5Row || null,
        },
        colors: {
          kpdColor: kpdColor || null,
          ratingColor: ratingColor || null,
        },
      },
      headerProps: {
        title: "Аналитика",
        settings: null,
        tabs: [
          {
            name: "Общая",
            settings: true,
            link: "/funnel/",
            nameClass: "analytic",
          },
          {
            name: "Трафик",
            settings: true,
            link: "/traffic/",
            nameClass: "analytic",
          },
          {
            name: "База",
            settings: true,
            link: "/additional/",
            nameClass: "analytic",
          },
        ],
        color: true,
        border: false,
      },
      selectProps: {
        selectsOnPage: [],
      },
    };
  },
});
